### busca usuario por id

GET http://localhost:3000/api/users

### obtener un usauario
GET http://localhost:3000/api/users/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crea un nuevo usuario

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nombre": "Bruno",
    "apellido": "Capiglioni",
    "tel": "3415673929",
    "email": "random1@gmail.com",
    "direccion": "Laprida 928"
}

### modificar un usuario ###

PUT http://localhost:3000/api/users/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "nombre": "Lionel",
    "apellido": "Messi",
    "tel": "341845673",
    "email": "lio@gmail.com",
    "direccion": "Ayacucho 2567"
}
### modificar un usuario PATCH ###

PATCH http://localhost:3000/api/users/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "nombre": "Andres",
    "apellido": "Messi",
    "tel": "341845888"
}

### eliminar un usuario
DELETE http://localhost:3000/api/users/a02b91bc-3769-4221-beb1-d7a3aeba7dad